alpha_1: 0.001  # meters/meter
alpha_2: 0.001 # meters/degree
alpha_3: 1.0   # degrees/meter
alpha_4: 0.001  # degrees/degree

# ICP PARAMETERS
max_correspondence_distance: 200.0 
max_iterations: 2000
ransac_iterations: 2000
ransac_outlier_threshold: 0.1
icp_score_scale: 200.0
icp_optimization_epsilon: 0.0000001
